export const locations = [
  {
    id: "causeway-bay",
    area: "Hong Kong Island",
    name: "Causeway Bay — Times Square",
    address: "city'super, B1, Times Square",
    hours: "Mon - Sun / 11:00-19:00",
    note: "Coffee Last Order 18:30",
  },
  {
    id: "kai-tak",
    area: "Kowloon",
    name: "Kai Tak Flagship Store — AIRSIDE",
    address: "city'super, B1/F, 2 Concorde Road, Kai Tak",
    hours: "Mon - Sun / 10:00-21:30",
    note: "Coffee Last Order 21:00",
  },
  {
    id: "tsim-sha-tsui",
    area: "Kowloon",
    name: "Tsim Sha Tsui — Harbour City",
    address: "city'super, Shop 3001, Gateway Arcade Level 3, Harbour City, TST",
    hours: "Mon - Sun / 09:00-20:00",
    note: "Coffee Last Order 19:30",
  },
  {
    id: "shatin",
    area: "New Territories",
    name: "Shatin — New Town Plaza",
    address: "city'super, Shop 204-214, L2, Phase 1, New Town Plaza, Shatin",
    hours: "Mon - Sun / 9:30-19:00",
    note: "Coffee Last Order 18:30",
  },
  {
    id: "tai-wai",
    area: "New Territories",
    name: "Tai Wai — The Wai",
    address: "Louder, Shop 328, L3, 18 Che Kung Miu Road",
    hours: "Mon - Sun / 11:30-19:30",
    note: "",
  },
]