export const products = [
  // ===== Espresso Beans =====
  {
    id: "espresso-winey",
    name: "NEW - Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Winey Blend - Espresso Beans",
    category: "espresso-beans",
    price: "From HK$380.00",
    originalPrice: null,
    image:
      "https://sofecoffee.com/cdn/shop/files/sofe_espresso_bean_300_winey_51ea2be5-372c-402d-a5db-b67dd42ceae0.jpg",
    href: "/products/new-winey-blend-拼配意式濃縮咖啡豆",
    badge: "NEW",
  },
  {
    id: "espresso-nutty",
    name: "NEW - Nutty Blend - Espresso Beans",
    category: "espresso-beans",
    price: "From HK$180.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_espresso_bean_300_nutty.jpg",
    href: "/products/nutty-blend-拼配意式濃縮咖啡豆",
    badge: "NEW",
  },
  {
    id: "espresso-fruity",
    name: "NEW - Fruity Blend - Espresso Beans",
    category: "espresso-beans",
    price: "From HK$180.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_espresso_bean_300_fruity.jpg",
    href: "/products/new-fruity-blend-拼配意式濃縮咖啡豆",
    badge: "NEW",
  },
  {
    id: "soe-brazil",
    name: "SOE - Single Origin Espresso Beans - Brazil",
    category: "espresso-beans",
    price: "From HK$250.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_espresso_bean_300_brazil.jpg",
    href: "/products/巴西-單品意式濃縮咖啡豆-副本",
    badge: null,
  },
  {
    id: "soe-ethiopia",
    name: "SOE - Single Origin Espresso Beans - Ethiopia",
    category: "espresso-beans",
    price: "From HK$250.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_espresso_bean_300_ethiopia.jpg",
    href: "/products/衣索比亞-單品意式濃縮咖啡豆-副本",
    badge: null,
  },

  // ===== Pour Over Beans =====
  {
    id: "pourover-peach",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Coffee Bean - Colombia (+ Peach)",
    category: "pour-over-beans",
    price: "HK$190.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_can_100g_photo02_mockop_peach.jpg",
    href: "/products/new-Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-咖啡豆-哥倫比亞-水蜜桃",
    badge: null,
  },
  {
    id: "pourover-strawberry",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Coffee Bean - Colombia (+ Strawberry)",
    category: "pour-over-beans",
    price: "HK$190.00",
    originalPrice: null,
    image:
      "https://sofecoffee.com/cdn/shop/files/sofe_can_100g_colombia_Strawberry_2025_01_VSCO_JPG.jpg",
    href: "/products/Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-咖啡豆-哥倫比亞-士多啤梨",
    badge: null,
  },
  {
    id: "pourover-honduras",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Coffee Bean - Honduras G1",
    category: "pour-over-beans",
    price: "HK$180.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/0A6A190D-C104-4DED-8DD9-82F07AFACF3A.webp",
    href: "/products/honduras-g1-100g-beans",
    badge: null,
  },
  {
    id: "pourover-panama",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Coffee Bean - Panama (Geisha)",
    category: "pour-over-beans",
    price: "HK$170.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_pbean_panama.jpg",
    href: "/products/panama-100g-beans",
    badge: null,
  },
  {
    id: "single-ethiopia",
    name: "Ethiopia - Single Origin Beans",
    category: "pour-over-beans",
    price: "HK$145.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_espresso_bean_150_ethiopia.jpg",
    href: "/products/衣索比亞-單品咖啡豆-150g",
    badge: null,
  },
  {
    id: "single-png",
    name: "Papua New Guinea - Single Origin Beans",
    category: "pour-over-beans",
    price: "HK$145.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_espresso_bean_150_png.jpg",
    href: "/products/巴布亞新幾內亞-單品咖啡豆-150g",
    badge: null,
  },
  {
    id: "single-kenya",
    name: "Kenya - Single Origin Beans",
    category: "pour-over-beans",
    price: "HK$145.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_espresso_bean_150_kenya.jpg",
    href: "/products/肯亞-單品咖啡豆-150g",
    badge: null,
  },
  {
    id: "single-colombia",
    name: "Colombia - Single Origin Beans",
    category: "pour-over-beans",
    price: "HK$145.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_espresso_bean_150_colombia.jpg",
    href: "/products/哥倫比亞-單品咖啡豆-150g",
    badge: null,
  },
  {
    id: "single-brazil",
    name: "Brazil - Single Origin Beans",
    category: "pour-over-beans",
    price: "HK$145.00",
    originalPrice: null,
    image: "https://placehold.co/400x400/1a2a1e/c8a45c?text=Brazil",
    href: "/products/巴西-單品咖啡豆-150g",
    badge: null,
  },
  {
    id: "single-mexico",
    name: "Mexico - Single Origin Beans",
    category: "pour-over-beans",
    price: "HK$145.00",
    originalPrice: null,
    image: "https://placehold.co/400x400/1e2a1a/c8a45c?text=Mexico",
    href: "/products/墨西哥-單品咖啡豆",
    badge: null,
  },

  // ===== Drip Bags =====
  {
    id: "drip-peach-single",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Drip Bag - Colombia (+ Peach)",
    category: "drip-bags",
    price: "HK$38.00",
    originalPrice: null,
    image:
      "https://sofecoffee.com/cdn/shop/files/sofe_premium_drip_bag_peach_deb0a418-ff6a-4bbc-a886-814bd61e105b.jpg",
    href: "/products/new-Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-咖啡掛耳包-哥倫比亞-士多啤梨-副本",
    badge: null,
  },
  {
    id: "drip-peach-5",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Drip Bag - Colombia (+ Peach) x5",
    category: "drip-bags",
    price: "HK$170.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_premium_prach_grip_bag_box_ai.png",
    href: "/products/new-Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-咖啡掛耳包-哥倫比亞-水蜜桃-5包裝",
    badge: null,
  },
  {
    id: "drip-strawberry-5",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Drip Bag - Colombia (+ Strawberry) x5",
    category: "drip-bags",
    price: "HK$170.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/3902518E-3131-4819-8F64-F93DD57584B8.jpg",
    href: "/products/Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-咖啡掛耳包-哥倫比亞-士多啤梨-5包裝",
    badge: null,
  },
  {
    id: "drip-honduras-5",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Drip Bag - Honduras G1 x5",
    category: "drip-bags",
    price: "HK$160.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/F2279D01-41B4-4A63-8077-038E41192B6D.jpg",
    href: "/products/Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-咖啡掛耳包-洪都拉斯-g1-副本",
    badge: null,
  },
  {
    id: "drip-panama-5",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Drip Bag - Panama (Geisha) x5",
    category: "drip-bags",
    price: "HK$150.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/3E86937C-B5D9-4F40-9987-DA4A1D9152C0.jpg",
    href: "/products/Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-咖啡掛耳包-巴拿馬-藝伎",
    badge: null,
  },
  {
    id: "drip-mandarin-5",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Drip Bag - Colombia (+ Mandarin) x5",
    category: "drip-bags",
    price: "HK$100.00",
    originalPrice: "HK$130.00",
    image: "https://sofecoffee.com/cdn/shop/files/sofe_premium_box_new_orange_pos_VSCO.jpg",
    href: "/products/Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-咖啡掛耳包-哥倫比亞-柑橘",
    badge: "Sale",
  },
  {
    id: "drip-nicaragua-5",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Drip Bag - Nicaragua x5",
    category: "drip-bags",
    price: "HK$120.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_premium_box_new_nicaragua_pos_VSCO.jpg",
    href: "/products/Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-咖啡掛耳包-尼加拉瓜",
    badge: null,
  },
  {
    id: "drip-10pack",
    name: "Drip Bag - 10 Pack Special",
    category: "drip-bags",
    price: "HK$180.00",
    originalPrice: "HK$200.00",
    image: "https://sofecoffee.com/cdn/shop/files/sofe_drip_bag_box_mockup_ai_pos_VSCO.jpg",
    href: "/products/10dbbox",
    badge: "Sale",
  },
  {
    id: "drip-ethiopia",
    name: "Coffee Drip Bag - Ethiopia",
    category: "drip-bags",
    price: "HK$120.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_drip_bag_pos_photo_ethiopia_VSCO.jpg",
    href: "/products/drip-bag-coffee-ethiopia",
    badge: null,
  },
  {
    id: "drip-kenya",
    name: "Coffee Drip Bag - Kenya",
    category: "drip-bags",
    price: "HK$120.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_drip_bag_pos_photo_kenya_VSCO.jpg",
    href: "/products/drip-bag-coffee-kenya",
    badge: null,
  },
  {
    id: "drip-png",
    name: "Coffee Drip Bag - Papua New Guinea",
    category: "drip-bags",
    price: "HK$120.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_drip_bag_pos_photo_png_VSCO.jpg",
    href: "/products/drip-bag-coffee-png",
    badge: null,
  },
  {
    id: "drip-colombia",
    name: "Coffee Drip Bag - Colombia",
    category: "drip-bags",
    price: "HK$120.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_drip_bag_pos_photo_colombia_VSCO.jpg",
    href: "/products/drip-bag-coffee-colombia",
    badge: null,
  },
  {
    id: "drip-brazil",
    name: "Coffee Drip Bag - Brazil",
    category: "drip-bags",
    price: "HK$120.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_drip_bag_pos_photo_brazil_VSCO.jpg",
    href: "/products/drip-bag-coffee-brazil",
    badge: null,
  },
  {
    id: "drip-mexico",
    name: "Coffee Drip Bag - Mexico",
    category: "drip-bags",
    price: "HK$120.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_drip_bag_pos_photo_mexico_VSCO.jpg",
    href: "/products/drip-bag-coffee-mexico",
    badge: null,
  },

  // ===== Cold Brew Bags =====
  {
    id: "coldbrew-ethiopia",
    name: "Cold Brew Bag - Ethiopia",
    category: "cold-brew-bags",
    price: "HK$120.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_cold_brew_bag_new_ethiopia_s.jpg",
    href: "/products/cold-brew-bag",
    badge: null,
  },
  {
    id: "coldbrew-mexico",
    name: "Cold Brew Bag - Mexico",
    category: "cold-brew-bags",
    price: "HK$120.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_cold_brew_bag_new_mexico_s.jpg",
    href: "/products/冷萃咖啡包-墨西哥",
    badge: null,
  },
  {
    id: "coldbrew-png",
    name: "Cold Brew Bag - Papua New Guinea",
    category: "cold-brew-bags",
    price: "HK$120.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_cold_brew_bag_new_png_s.jpg",
    href: "/products/冷萃咖啡包-巴布亞新幾內亞",
    badge: null,
  },
  {
    id: "coldbrew-kenya",
    name: "Cold Brew Bag - Kenya AA",
    category: "cold-brew-bags",
    price: "HK$120.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_cold_brew_bag_new_kenya_s.jpg",
    href: "/products/冷萃咖啡包-肯亞-aa",
    badge: null,
  },
  {
    id: "coldbrew-colombia",
    name: "Cold Brew Bag - Colombia",
    category: "cold-brew-bags",
    price: "HK$120.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_cold_brew_bag_new_Colombia_s.jpg",
    href: "/products/冷萃咖啡包-哥倫比亞",
    badge: null,
  },
  {
    id: "coldbrew-brazil",
    name: "Cold Brew Bag - Brazil",
    category: "cold-brew-bags",
    price: "HK$120.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_cold_brew_bag_new_brazil_s.jpg",
    href: "/products/冷萃咖啡包-巴西",
    badge: null,
  },
  {
    id: "coldbrew-premium-honduras",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Cold Brew Bag - Honduras G1",
    category: "cold-brew-bags",
    price: "HK$180.00",
    originalPrice: null,
    image:
      "https://sofecoffee.com/cdn/shop/files/sofe_cold_brew_bag_premium_honduras_small_bbb3d656-1a40-4e44-94e9-43f25d7c3d7d.jpg",
    href: "/products/Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-冷萃咖啡包-洪都拉斯-g1",
    badge: null,
  },
  {
    id: "coldbrew-premium-panama",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Cold Brew Bag - Panama (Geisha)",
    category: "cold-brew-bags",
    price: "HK$170.00",
    originalPrice: null,
    image:
      "https://sofecoffee.com/cdn/shop/files/sofe_cold_brew_bag_premium_panama_small_7078db87-d52c-4edc-8c7d-c15def17f100.jpg",
    href: "/products/Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-冷萃咖啡包-巴拿馬-藝伎",
    badge: null,
  },
  {
    id: "coldbrew-premium-mandarin",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Cold Brew Bag - Colombia (+ Mandarin)",
    category: "cold-brew-bags",
    price: "HK$128.00",
    originalPrice: "HK$160.00",
    image:
      "https://sofecoffee.com/cdn/shop/files/sofe_cold_brew_bag_premium_colombia_small_8a624fb2-2cb4-4962-9e87-7f71a161d21d.jpg",
    href: "/products/Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-冷萃咖啡包-哥倫比亞-柑橘",
    badge: "Sale",
  },
  {
    id: "coldbrew-premium-nicaragua",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Cold Brew Bag - Nicaragua",
    category: "cold-brew-bags",
    price: "HK$150.00",
    originalPrice: null,
    image:
      "https://sofecoffee.com/cdn/shop/files/sofe_cold_brew_bag_premium_nicaragua_small_b891f8fe-d1c6-49d0-9c49-e8a78d909ffb.jpg",
    href: "/products/Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-冷萃咖啡包-尼加拉瓜",
    badge: null,
  },
  {
    id: "coldbrew-premium-strawberry",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Cold Brew Bag - Colombia (+ Strawberry)",
    category: "cold-brew-bags",
    price: "HK$190.00",
    originalPrice: null,
    image:
      "https://sofecoffee.com/cdn/shop/files/sofe_cold_brew_bag_new_2025_premium_strawberry_small_ea79f6b6-87e1-46fe-b7f9-50cdebdd0e26.jpg",
    href: "/products/Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-冷萃咖啡包-哥倫比亞-士多啤梨",
    badge: null,
  },
  {
    id: "coldbrew-premium-peach",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Cold Brew Bag - Colombia (+ Peach)",
    category: "cold-brew-bags",
    price: "HK$190.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_cold_brew_bag_new_peach.jpg",
    href: "/products/Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-冷萃咖啡包-哥倫比亞-水蜜桃",
    badge: null,
  },
  {
    id: "coldbrew-oatside",
    name: "Oatside Cold Brew Bag - for Cold Brew Latte (20g x 5)",
    category: "cold-brew-bags",
    price: "HK$120.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_latte_cold_brew_bag_2.jpg",
    href: "/products/cold-brew-bag-oatside",
    badge: null,
  },
  {
    id: "coldbrew-set",
    name: "Cold Brew Bag - Special Set",
    category: "cold-brew-bags",
    price: "HK$380.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_cold_brew_set_web.jpg",
    href: "/products/3cbbset",
    badge: null,
  },

  // ===== Coffee Tools =====
  {
    id: "tool-varia-vs3",
    name: "Varia - VS3 Electric Grinder (2nd Gen) - Black",
    category: "coffee-tools",
    price: "HK$2,350.00",
    originalPrice: "HK$2,450.00",
    image: "https://sofecoffee.com/cdn/shop/files/vs3_6.jpg",
    href: "/products/varia-vs3-electric-grinder",
    badge: "Sale",
  },
  {
    id: "tool-hand-grinder-v2",
    name: "SOFE COFFEE Hand Grinder V2 - External Adjustable",
    category: "coffee-tools",
    price: "HK$680.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/grinder_v2_1.jpg",
    href: "/products/grinderv2",
    badge: null,
  },
  {
    id: "tool-ceramic-dripper",
    name: "Japan Sanyo Arita Yaki Petal Dripper - Black Limited",
    category: "coffee-tools",
    price: "HK$288.00",
    originalPrice: "HK$320.00",
    image: "https://sofecoffee.com/cdn/shop/files/cafec_dripper_2.jpg",
    href: "/products/cafec-flower-dripper-matte-black-v01",
    badge: "Sale",
  },
  {
    id: "tool-deep45-dripper",
    name: "20% OFF - Japan Sanyo DEEP 45 Petal Dripper",
    category: "coffee-tools",
    price: "HK$174.00",
    originalPrice: "HK$218.00",
    image: "https://sofecoffee.com/cdn/shop/files/deep45_1.jpg",
    href: "/products/deep-45",
    badge: "Sale",
  },
  {
    id: "tool-tritan-dripper",
    name: "NEW - Japan Sanyo Tritan Petal Dripper - Translucent Black",
    category: "coffee-tools",
    price: "HK$188.00",
    originalPrice: null,
    image:
      "https://sofecoffee.com/cdn/shop/files/sofe_cafec_dripper_tritan_02_51bc3bdf-c9fe-4bc1-b0c0-fcd4c1ac94bb.png",
    href: "/products/日本三洋tritan花瓣濾杯-半透明黑色",
    badge: "NEW",
  },
  {
    id: "tool-coffee-server",
    name: "Black Glass Coffee Server",
    category: "coffee-tools",
    price: "HK$88.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_server_black_2.jpg",
    href: "/products/coffee-glass-server",
    badge: null,
  },
  {
    id: "tool-drip-stand",
    name: "SOFE COFFEE Drip Bag Stand",
    category: "coffee-tools",
    price: "HK$65.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_db_holder6.jpg",
    href: "/products/sofe-drip-bag-holder",
    badge: null,
  },
  {
    id: "tool-coffee-scale",
    name: "The Artisan Barista - Coffee Scale with Timer",
    category: "coffee-tools",
    price: "HK$499.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/scale_2.jpg",
    href: "/products/the-artisan-barista-scale",
    badge: null,
  },
  {
    id: "tool-filter-paper",
    name: "Japan Sanyo Abaca+ V60 Filter Paper (100 Sheets)",
    category: "coffee-tools",
    price: "HK$80.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/IMG-4505.jpg",
    href: "/products/日本三洋-abaca-棉麻v60手沖咖啡濾紙-100張",
    badge: null,
  },
  {
    id: "tool-coldbrew-glass",
    name: "SOFE COFFEE Cold Brew Glass (Limited Edition)",
    category: "coffee-tools",
    price: "HK$98.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_cold_brew_cup_photo_square_character_mockup.jpg",
    href: "/products/cold-brew-cup",
    badge: null,
  },

  // ===== Premium Drip Bag Singles =====
  {
    id: "drip-premium-honduras-single",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Drip Bag - Honduras G1",
    category: "drip-bags",
    price: "HK$160.00",
    originalPrice: null,
    image:
      "https://sofecoffee.com/cdn/shop/files/sofe_premium_drip_bag_honduras_VSCO.jpg",
    href: "/products/Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-咖啡掛耳包-洪都拉斯-g1",
    badge: null,
  },
  {
    id: "drip-premium-panama-single",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Drip Bag - Panama (Geisha)",
    category: "drip-bags",
    price: "HK$150.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_premium_drip_bag_panama_VSCO.jpg",
    href: "/products/Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-咖啡掛耳包-巴拿馬-藝伎-5包裝-副本",
    badge: null,
  },
  {
    id: "drip-premium-mandarin-single",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Drip Bag - Colombia (+ Mandarin)",
    category: "drip-bags",
    price: "HK$100.00",
    originalPrice: "HK$130.00",
    image: "https://sofecoffee.com/cdn/shop/files/sofe_premium_drip_bag_colombia_VSCO.jpg",
    href: "/products/Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-咖啡掛耳包-哥倫比亞-柑橘-1",
    badge: "Sale",
  },
  {
    id: "drip-premium-nicaragua-single",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Drip Bag - Nicaragua",
    category: "drip-bags",
    price: "HK$120.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_premium_drip_bag_nicatagua_VSCO.jpg",
    href: "/products/Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-咖啡掛耳包-尼加拉瓜-1",
    badge: null,
  },
  {
    id: "drip-premium-strawberry-single",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Drip Bag - Colombia (+ Strawberry)",
    category: "drip-bags",
    price: "HK$38.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_premium_drip_bag_strawberry_VSCO.jpg",
    href: "/products/Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-咖啡掛耳包-哥倫比亞-士多啤梨-副本",
    badge: null,
  },

  // ===== Cascara Tea =====
  {
    id: "cascara",
    name: "Cascara - Coffee Cherry Fruit Tea",
    category: "cascara-tea",
    price: "HK$120.00",
    originalPrice: "HK$150.00",
    image: "https://sofecoffee.com/cdn/shop/files/sofe_cascura_can_50g_2025_pos_VSCO.jpg",
    href: "#",
    badge: "Sale",
  },

  // ===== Sofe Credits =====
  {
    id: "sofe-credits",
    name: "Sofe Credits - Stored Value Card",
    category: "sofe-credits",
    price: "HK$500.00",
    originalPrice: null,
    image: "https://placehold.co/400x400/1a1a2e/c8a45c?text=Sofe+Credits",
    href: "/collections/sofe-credits",
    badge: null,
  },
]

export const categories = [
  { id: "espresso-beans", name: "NEW - Espresso Beans", slug: "/collections/espresso-beans" },
  { id: "pour-over-beans", name: "Selected Coffee Beans", slug: "/collections/selected-beans" },
  { id: "drip-bags", name: "Coffee Drip Bag", slug: "/collections/coffee-drip-bag" },
  { id: "cold-brew-bags", name: "Cold Brew Bag", slug: "/collections/cold-brew-bag" },
  { id: "coffee-tools", name: "Coffee Tools", slug: "/collections/coffee-tools" },
  { id: "cascara-tea", name: "Cascara Tea", slug: "/collections/cascara-tea" },
  { id: "sofe-credits", name: "Sofe Credits", slug: "/collections/sofe-credits" },
]

export function getProductsByCategory(category) {
  return products.filter((p) => p.category === category)
}

/**
 * Map a collection slug (the last segment of /collections/:slug) to a category object.
 * Returns undefined if no match.
 */
export function getCategoryBySlug(slug) {
  return categories.find((c) => {
    const parts = c.slug.split("/")
    return parts[parts.length - 1] === slug
  })
}

export const subscriptions = [
  {
    id: "sub-db-3",
    name: "3 Months Subscription",
    type: "Coffee Drip Bag",
    price: "HK$1,450.00",
    originalPrice: "HK$1,800.00",
    image: "https://placehold.co/400x400/1a2a1e/c8a45c?text=3+Months+DB",
    href: "#",
    save: "Save 19%",
  },
  {
    id: "sub-db-6",
    name: "6 Months Subscription",
    type: "Coffee Drip Bag",
    price: "HK$2,580.00",
    originalPrice: "HK$3,600.00",
    image: "https://placehold.co/400x400/1e2a1a/c8a45c?text=6+Months+DB",
    href: "#",
    save: "Save 28%",
  },
  {
    id: "sub-db-12",
    name: "12 Months Subscription",
    type: "Coffee Drip Bag",
    price: "HK$4,500.00",
    originalPrice: "HK$7,200.00",
    image: "https://placehold.co/400x400/2a1e1a/c8a45c?text=12+Months+DB",
    href: "#",
    save: "Save 37%",
  },
  {
    id: "sub-beans-3",
    name: "3 Months Subscription",
    type: "Pour Over Coffee Beans",
    price: "HK$780.00",
    originalPrice: "HK$870.00",
    image: "https://placehold.co/400x400/1a1a2e/c8a45c?text=3+Months+Beans",
    href: "#",
    save: "Save 10%",
  },
  {
    id: "sub-beans-6",
    name: "6 Months Subscription",
    type: "Pour Over Coffee Beans",
    price: "HK$1,380.00",
    originalPrice: "HK$1,740.00",
    image: "https://placehold.co/400x400/2e1a1a/c8a45c?text=6+Months+Beans",
    href: "#",
    save: "Save 21%",
  },
  {
    id: "sub-beans-12",
    name: "12 Months Subscription",
    type: "Pour Over Coffee Beans",
    price: "HK$2,680.00",
    originalPrice: "HK$3,480.00",
    image: "https://placehold.co/400x400/1a2e2e/c8a45c?text=12+Months+Beans",
    href: "#",
    save: "Save 23%",
  },
]