export const products = [
  // ===== Espresso Beans =====
  {
    id: "espresso-winey",
    name: "NEW - Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Winey Blend - Espresso Beans",
    category: "espresso-beans",
    price: "From HK$380.00",
    originalPrice: null,
    image:
      "https://sofecoffee.com/cdn/shop/files/sofe_espresso_bean_300_winey_51ea2be5-372c-402d-a5db-b67dd42ceae0.jpg",
    href: "/products/winey-blend",
    shopifySlug: "new-winey-blend-拼配意式濃縮咖啡豆",
    badge: "NEW",
  },
  {
    id: "espresso-nutty",
    name: "NEW - Nutty Blend - Espresso Beans",
    category: "espresso-beans",
    price: "From HK$180.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_espresso_bean_300_nutty.jpg",
    href: "/products/nutty-blend",
    shopifySlug: "nutty-blend-拼配意式濃縮咖啡豆",
    badge: "NEW",
  },
  {
    id: "espresso-fruity",
    name: "NEW - Fruity Blend - Espresso Beans",
    category: "espresso-beans",
    price: "From HK$180.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_espresso_bean_300_fruity.jpg",
    href: "/products/fruity-blend",
    shopifySlug: "new-fruity-blend-拼配意式濃縮咖啡豆",
    badge: "NEW",
  },
  {
    id: "soe-brazil",
    name: "SOE - Single Origin Espresso Beans - Brazil",
    category: "espresso-beans",
    price: "From HK$250.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_espresso_bean_300_brazil.jpg",
    href: "/products/soe-brazil",
    shopifySlug: "巴西-單品意式濃縮咖啡豆-副本",
    badge: null,
  },
  {
    id: "soe-ethiopia",
    name: "SOE - Single Origin Espresso Beans - Ethiopia",
    category: "espresso-beans",
    price: "From HK$250.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_espresso_bean_300_ethiopia.jpg",
    href: "/products/soe-ethiopia",
    shopifySlug: "衣索比亞-單品意式濃縮咖啡豆-副本",
    badge: null,
  },

  // ===== Pour Over Beans =====
  {
    id: "pourover-peach",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Coffee Bean - Colombia (+ Peach)",
    category: "pour-over-beans",
    price: "HK$190.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_can_100g_photo02_mockop_peach.jpg",
    href: "/products/premium-peach-beans",
    shopifySlug: "new-Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-咖啡豆-哥倫比亞-水蜜桃",
    badge: "NEW",
  },
  {
    id: "pourover-strawberry",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Coffee Bean - Colombia (+ Strawberry)",
    category: "pour-over-beans",
    price: "HK$190.00",
    originalPrice: null,
    image:
      "https://sofecoffee.com/cdn/shop/files/sofe_can_100g_colombia_Strawberry_2025_01_VSCO_JPG.jpg",
    href: "/products/premium-strawberry-beans",
    shopifySlug: "Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-咖啡豆-哥倫比亞-士多啤梨",
    badge: "NEW",
  },
  {
    id: "pourover-honduras",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Coffee Bean - Honduras G1",
    category: "pour-over-beans",
    price: "HK$180.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/0A6A190D-C104-4DED-8DD9-82F07AFACF3A.webp",
    href: "/products/honduras-g1-100g-beans",
    badge: "NEW",
  },
  {
    id: "pourover-panama",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Coffee Bean - Panama (Geisha)",
    category: "pour-over-beans",
    price: "HK$170.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_pbean_panama.jpg",
    href: "/products/panama-100g-beans",
    badge: null,
  },
  {
    id: "single-ethiopia",
    name: "Ethiopia - Single Origin Beans",
    category: "pour-over-beans",
    price: "HK$145.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_espresso_bean_150_ethiopia.jpg",
    href: "/products/single-ethiopia",
    shopifySlug: "衣索比亞-單品咖啡豆-150g",
    badge: null,
  },
  {
    id: "single-png",
    name: "Papua New Guinea - Single Origin Beans",
    category: "pour-over-beans",
    price: "HK$145.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_espresso_bean_150_png.jpg",
    href: "/products/single-png",
    shopifySlug: "巴布亞新幾內亞-單品咖啡豆-150g",
    badge: null,
  },
  {
    id: "single-kenya",
    name: "Kenya - Single Origin Beans",
    category: "pour-over-beans",
    price: "HK$145.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_espresso_bean_150_kenya.jpg",
    href: "/products/single-kenya",
    shopifySlug: "肯亞-單品咖啡豆-150g",
    badge: null,
  },
  {
    id: "single-colombia",
    name: "Colombia - Single Origin Beans",
    category: "pour-over-beans",
    price: "HK$145.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_espresso_bean_150_colombia.jpg",
    href: "/products/single-colombia",
    shopifySlug: "哥倫比亞-單品咖啡豆-150g",
    badge: null,
  },
  {
    id: "single-brazil",
    name: "Brazil - Single Origin Beans",
    category: "pour-over-beans",
    price: "HK$145.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_espresso_bean_150_brazil.jpg",
    href: "/products/single-brazil",
    shopifySlug: "巴西-單品咖啡豆-150g",
    badge: null,
  },
  {
    id: "single-mexico",
    name: "Mexico - Single Origin Beans",
    category: "pour-over-beans",
    price: "HK$145.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_espresso_bean_150_mexica.jpg",
    href: "/products/single-mexico",
    shopifySlug: "墨西哥-單品咖啡豆",
    badge: null,
  },

  // ===== Drip Bags =====
  {
    id: "drip-peach-single",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Drip Bag - Colombia (+ Peach)",
    category: "drip-bags",
    price: "HK$38.00",
    originalPrice: null,
    image:
      "https://sofecoffee.com/cdn/shop/files/sofe_premium_drip_bag_peach_deb0a418-ff6a-4bbc-a886-814bd61e105b.jpg",
    href: "/products/premium-drip-peach",
    shopifySlug: "new-Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-咖啡掛耳包-哥倫比亞-士多啤梨-副本",
    badge: "NEW",
  },
  {
    id: "drip-peach-5",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Drip Bag - Colombia (+ Peach) x5",
    category: "drip-bags",
    price: "HK$170.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_premium_prach_grip_bag_box_ai.png",
    href: "/products/premium-drip-peach-5",
    shopifySlug: "new-Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-咖啡掛耳包-哥倫比亞-水蜜桃-5包裝",
    badge: "NEW",
  },
  {
    id: "drip-strawberry-5",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Drip Bag - Colombia (+ Strawberry) x5",
    category: "drip-bags",
    price: "HK$170.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/3902518E-3131-4819-8F64-F93DD57584B8.jpg",
    href: "/products/premium-drip-strawberry-5",
    shopifySlug: "Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-咖啡掛耳包-哥倫比亞-士多啤梨-5包裝",
    badge: "NEW",
  },
  {
    id: "drip-honduras-5",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Drip Bag - Honduras G1 x5",
    category: "drip-bags",
    price: "HK$160.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/F2279D01-41B4-4A63-8077-038E41192B6D.jpg",
    href: "/products/premium-drip-honduras-5",
    shopifySlug: "Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-咖啡掛耳包-洪都拉斯-g1-副本",
    badge: "NEW",
  },
  {
    id: "drip-panama-5",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Drip Bag - Panama (Geisha) x5",
    category: "drip-bags",
    price: "HK$150.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/3E86937C-B5D9-4F40-9987-DA4A1D9152C0.jpg",
    href: "/products/premium-drip-panama-5",
    shopifySlug: "Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-咖啡掛耳包-巴拿馬-藝伎",
    badge: null,
  },
  {
    id: "drip-mandarin-5",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Drip Bag - Colombia (+ Mandarin) x5",
    category: "drip-bags",
    price: "HK$100.00",
    originalPrice: "HK$130.00",
    image: "https://sofecoffee.com/cdn/shop/files/sofe_premium_box_new_orange_pos_VSCO.jpg",
    href: "/products/premium-drip-mandarin-5",
    shopifySlug: "Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-咖啡掛耳包-哥倫比亞-柑橘",
    badge: "Sale",
  },
  {
    id: "drip-nicaragua-5",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Drip Bag - Nicaragua x5",
    category: "drip-bags",
    price: "HK$120.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_premium_box_new_nicaragua_pos_VSCO.jpg",
    href: "/products/premium-drip-nicaragua-5",
    shopifySlug: "Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-咖啡掛耳包-尼加拉瓜",
    badge: null,
  },
  {
    id: "drip-10pack",
    name: "Drip Bag - 10 Pack Special",
    category: "drip-bags",
    price: "HK$180.00",
    originalPrice: "HK$200.00",
    image: "https://sofecoffee.com/cdn/shop/files/sofe_drip_bag_box_mockup_ai_pos_VSCO.jpg",
    href: "/products/10dbbox",
    badge: "Sale",
  },
  {
    id: "drip-ethiopia",
    name: "Coffee Drip Bag - Ethiopia",
    category: "drip-bags",
    price: "HK$120.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_drip_bag_pos_photo_ethiopia_VSCO.jpg",
    href: "/products/drip-bag-ethiopia",
    badge: null,
  },
  {
    id: "drip-kenya",
    name: "Coffee Drip Bag - Kenya",
    category: "drip-bags",
    price: "HK$120.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_drip_bag_pos_photo_kenya_VSCO.jpg",
    href: "/products/drip-bag-kenya",
    badge: null,
  },
  {
    id: "drip-png",
    name: "Coffee Drip Bag - Papua New Guinea",
    category: "drip-bags",
    price: "HK$120.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_drip_bag_pos_photo_png_VSCO.jpg",
    href: "/products/drip-bag-png",
    badge: null,
  },
  {
    id: "drip-colombia",
    name: "Coffee Drip Bag - Colombia",
    category: "drip-bags",
    price: "HK$120.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_drip_bag_pos_photo_colombia_VSCO.jpg",
    href: "/products/drip-bag-colombia",
    badge: null,
  },
  {
    id: "drip-brazil",
    name: "Coffee Drip Bag - Brazil",
    category: "drip-bags",
    price: "HK$120.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_drip_bag_pos_photo_brazil_VSCO.jpg",
    href: "/products/drip-bag-brazil",
    badge: null,
  },
  {
    id: "drip-mexico",
    name: "Coffee Drip Bag - Mexico",
    category: "drip-bags",
    price: "HK$120.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_drip_bag_pos_photo_mexico_VSCO.jpg",
    href: "/products/drip-bag-mexico",
    badge: null,
  },

  // ===== Cold Brew Bags =====
  {
    id: "coldbrew-ethiopia",
    name: "Cold Brew Bag - Ethiopia",
    category: "cold-brew-bags",
    price: "HK$120.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_cold_brew_bag_new_ethiopia_s.jpg",
    href: "/products/cold-brew-ethiopia",
    badge: null,
  },
  {
    id: "coldbrew-mexico",
    name: "Cold Brew Bag - Mexico",
    category: "cold-brew-bags",
    price: "HK$120.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_cold_brew_bag_new_mexico_s.jpg",
    href: "/products/cold-brew-mexico",
    shopifySlug: "冷萃咖啡包-墨西哥",
    badge: null,
  },
  {
    id: "coldbrew-png",
    name: "Cold Brew Bag - Papua New Guinea",
    category: "cold-brew-bags",
    price: "HK$120.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_cold_brew_bag_new_png_s.jpg",
    href: "/products/cold-brew-png",
    shopifySlug: "冷萃咖啡包-巴布亞新幾內亞",
    badge: null,
  },
  {
    id: "coldbrew-kenya",
    name: "Cold Brew Bag - Kenya AA",
    category: "cold-brew-bags",
    price: "HK$120.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_cold_brew_bag_new_kenya_s.jpg",
    href: "/products/cold-brew-kenya",
    shopifySlug: "冷萃咖啡包-肯亞-aa",
    badge: null,
  },
  {
    id: "coldbrew-colombia",
    name: "Cold Brew Bag - Colombia",
    category: "cold-brew-bags",
    price: "HK$120.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_cold_brew_bag_new_Colombia_s.jpg",
    href: "/products/cold-brew-colombia",
    shopifySlug: "冷萃咖啡包-哥倫比亞",
    badge: null,
  },
  {
    id: "coldbrew-brazil",
    name: "Cold Brew Bag - Brazil",
    category: "cold-brew-bags",
    price: "HK$120.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_cold_brew_bag_new_brazil_s.jpg",
    href: "/products/cold-brew-brazil",
    shopifySlug: "冷萃咖啡包-巴西",
    badge: null,
  },
  {
    id: "coldbrew-premium-honduras",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Cold Brew Bag - Honduras G1",
    category: "cold-brew-bags",
    price: "HK$180.00",
    originalPrice: null,
    image:
      "https://sofecoffee.com/cdn/shop/files/sofe_cold_brew_bag_premium_honduras_small_bbb3d656-1a40-4e44-94e9-43f25d7c3d7d.jpg",
    href: "/products/premium-coldbrew-honduras",
    shopifySlug: "Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-冷萃咖啡包-洪都拉斯-g1",
    badge: "NEW",
  },
  {
    id: "coldbrew-premium-panama",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Cold Brew Bag - Panama (Geisha)",
    category: "cold-brew-bags",
    price: "HK$170.00",
    originalPrice: null,
    image:
      "https://sofecoffee.com/cdn/shop/files/sofe_cold_brew_bag_premium_panama_small_7078db87-d52c-4edc-8c7d-c15def17f100.jpg",
    href: "/products/premium-coldbrew-panama",
    shopifySlug: "Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-冷萃咖啡包-巴拿馬-藝伎",
    badge: "NEW",
  },
  {
    id: "coldbrew-premium-mandarin",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Cold Brew Bag - Colombia (+ Mandarin)",
    category: "cold-brew-bags",
    price: "HK$128.00",
    originalPrice: "HK$160.00",
    image:
      "https://sofecoffee.com/cdn/shop/files/sofe_cold_brew_bag_premium_colombia_small_8a624fb2-2cb4-4962-9e87-7f71a161d21d.jpg",
    href: "/products/premium-coldbrew-mandarin",
    shopifySlug: "Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-冷萃咖啡包-哥倫比亞-柑橘",
    badge: "Sale",
  },
  {
    id: "coldbrew-premium-nicaragua",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Cold Brew Bag - Nicaragua",
    category: "cold-brew-bags",
    price: "HK$150.00",
    originalPrice: null,
    image:
      "https://sofecoffee.com/cdn/shop/files/sofe_cold_brew_bag_premium_nicaragua_small_b891f8fe-d1c6-49d0-9c49-e8a78d909ffb.jpg",
    href: "/products/premium-coldbrew-nicaragua",
    shopifySlug: "Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-冷萃咖啡包-尼加拉瓜",
    badge: null,
  },
  {
    id: "coldbrew-premium-strawberry",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Cold Brew Bag - Colombia (+ Strawberry)",
    category: "cold-brew-bags",
    price: "HK$190.00",
    originalPrice: null,
    image:
      "https://sofecoffee.com/cdn/shop/files/sofe_cold_brew_bag_new_2025_premium_strawberry_small_ea79f6b6-87e1-46fe-b7f9-50cdebdd0e26.jpg",
    href: "/products/premium-coldbrew-strawberry",
    shopifySlug: "Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-冷萃咖啡包-哥倫比亞-士多啤梨",
    badge: "NEW",
  },
  {
    id: "coldbrew-premium-peach",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Cold Brew Bag - Colombia (+ Peach)",
    category: "cold-brew-bags",
    price: "HK$190.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_cold_brew_bag_new_peach.jpg",
    href: "/products/premium-coldbrew-peach",
    shopifySlug: "Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-冷萃咖啡包-哥倫比亞-水蜜桃",
    badge: "NEW",
  },
  {
    id: "coldbrew-oatside",
    name: "Oatside Cold Brew Bag - for Cold Brew Latte (20g x 5)",
    category: "cold-brew-bags",
    price: "HK$120.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_latte_cold_brew_bag_2.jpg",
    href: "/products/cold-brew-oatside",
    badge: null,
  },
  {
    id: "coldbrew-set",
    name: "Cold Brew Bag - Special Set",
    category: "cold-brew-bags",
    price: "HK$380.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_cold_brew_set_web.jpg",
    href: "/products/3cbbset",
    badge: null,
  },

  // ===== Huskee =====
	  {
	    id: "huskee-6oz",
	    name: "Huskee Cup - 6oz",
	    category: "huskee",
	    price: "HK$130.00",
	    originalPrice: null,
	    image: "https://sofecoffee.com/cdn/shop/files/huskee_6oz_N.jpg",
	    href: "/products/huskee-cup-with-lid-6oz",
	    badge: null,
	  },
	  {
	    id: "huskee-8oz",
	    name: "Huskee Cup - 8oz",
	    category: "huskee",
	    price: "HK$150.00",
	    originalPrice: null,
	    image: "https://sofecoffee.com/cdn/shop/files/huskee_8oz_N.jpg",
	    href: "/products/huskee-cup-with-lid-8oz",
	    badge: null,
	  },
	  {
	    id: "huskee-12oz",
	    name: "Huskee Cup - 12oz",
	    category: "huskee",
	    price: "HK$170.00",
	    originalPrice: null,
	    image: "https://sofecoffee.com/cdn/shop/files/huskee_12oz_N.jpg",
	    href: "/products/huskee-cup-with-lid-12oz",
	    badge: null,
	  },
	  {
	    id: "huskee-espresso-set",
	    name: "Huskee Cup Espresso Set - 3oz x2",
	    category: "huskee",
	    price: "HK$280.00",
	    originalPrice: null,
	    image: "https://sofecoffee.com/cdn/shop/files/huskee_3oz_N_set.jpg",
	    href: "/products/huskee-cup-espresso-set",
	    badge: null,
	  },
	  {
	    id: "huskee-renew-8oz",
	    name: "HuskeeRenew Cup - 8oz",
	    category: "huskee",
	    price: "HK$180.00",
	    originalPrice: null,
	    image: "https://sofecoffee.com/cdn/shop/files/huskee_renew_8oz_smoke.jpg",
	    href: "/products/huskee-renew-cup-8oz",
	    badge: null,
	  },
	  {
	    id: "huskee-renew-12oz",
	    name: "HuskeeRenew Cup - 12oz",
	    category: "huskee",
	    price: "HK$200.00",
	    originalPrice: null,
	    image: "https://sofecoffee.com/cdn/shop/files/huskee_renew_12oz_smoke.jpg",
	    href: "/products/huskee-renew-cup-12oz",
	    badge: null,
	  },

	  // ===== Coffee Tools =====
  {
    id: "tool-varia-vs3",
    name: "Varia - VS3 Electric Grinder (2nd Gen) - Black",
    category: "coffee-tools",
    price: "HK$2,350.00",
    originalPrice: "HK$2,450.00",
    image: "https://sofecoffee.com/cdn/shop/files/vs3_6.jpg",
    href: "/products/varia-vs3-electric-grinder",
    badge: "Sale",
  },
  {
    id: "tool-hand-grinder-v2",
    name: "SOFE COFFEE Hand Grinder V2 - External Adjustable",
    category: "coffee-tools",
    price: "HK$680.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/grinder_v2_1.jpg",
    href: "/products/hand-grinder-v2",
    badge: null,
  },
  {
    id: "tool-ceramic-dripper",
    name: "Japan Sanyo Arita Yaki Petal Dripper - Black Limited",
    category: "coffee-tools",
    price: "HK$288.00",
    originalPrice: "HK$320.00",
    image: "https://sofecoffee.com/cdn/shop/files/cafec_dripper_2.jpg",
    href: "/products/ceramic-dripper",
    badge: "Sale",
  },
  {
    id: "tool-deep45-dripper",
    name: "20% OFF - Japan Sanyo DEEP 45 Petal Dripper",
    category: "coffee-tools",
    price: "HK$174.00",
    originalPrice: "HK$218.00",
    image: "https://sofecoffee.com/cdn/shop/files/deep45_1.jpg",
    href: "/products/deep-45-dripper",
    badge: "Sale",
  },
  {
    id: "tool-tritan-dripper",
    name: "NEW - Japan Sanyo Tritan Petal Dripper - Translucent Black",
    category: "coffee-tools",
    price: "HK$188.00",
    originalPrice: null,
    image:
      "https://sofecoffee.com/cdn/shop/files/sofe_cafec_dripper_tritan_02_51bc3bdf-c9fe-4bc1-b0c0-fcd4c1ac94bb.png",
    href: "/products/tritan-dripper",
    shopifySlug: "日本三洋tritan花瓣濾杯-半透明黑色",
    badge: "NEW",
  },
  {
    id: "tool-coffee-server",
    name: "Black Glass Coffee Server",
    category: "coffee-tools",
    price: "HK$88.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_server_black_2.jpg",
    href: "/products/coffee-server",
    badge: null,
  },
  {
    id: "tool-drip-stand",
    name: "SOFE COFFEE Drip Bag Stand",
    category: "coffee-tools",
    price: "HK$65.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_db_holder6.jpg",
    href: "/products/drip-stand",
    badge: null,
  },
  {
    id: "tool-coffee-scale",
    name: "The Artisan Barista - Coffee Scale with Timer",
    category: "coffee-tools",
    price: "HK$499.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/scale_2.jpg",
    href: "/products/barista-scale",
    badge: null,
  },
  {
    id: "tool-filter-paper",
    name: "Japan Sanyo Abaca+ V60 Filter Paper (100 Sheets)",
    category: "coffee-tools",
    price: "HK$80.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/IMG-4505.jpg",
    href: "/products/filter-paper",
    shopifySlug: "日本三洋-abaca-棉麻v60手沖咖啡濾紙-100張",
    badge: null,
  },
  {
    id: "tool-coldbrew-glass",
    name: "SOFE COFFEE Cold Brew Glass (Limited Edition)",
    category: "coffee-tools",
    price: "HK$98.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_cold_brew_cup_photo_square_character_mockup.jpg",
    href: "/products/cold-brew-glass",
    badge: null,
  },

  // ===== Premium Drip Bag Singles =====
  {
    id: "drip-premium-honduras-single",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Drip Bag - Honduras G1",
    category: "drip-bags",
    price: "HK$160.00",
    originalPrice: null,
    image:
      "https://sofecoffee.com/cdn/shop/files/sofe_premium_drip_bag_honduras_VSCO.jpg",
    href: "/products/premium-drip-honduras-single",
    shopifySlug: "Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-咖啡掛耳包-洪都拉斯-g1",
    badge: null,
  },
  {
    id: "drip-premium-panama-single",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Drip Bag - Panama (Geisha)",
    category: "drip-bags",
    price: "HK$150.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_premium_drip_bag_panama_VSCO.jpg",
    href: "/products/premium-drip-panama-single",
    shopifySlug: "Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-咖啡掛耳包-巴拿馬-藝伎-5包裝-副本",
    badge: null,
  },
  {
    id: "drip-premium-mandarin-single",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Drip Bag - Colombia (+ Mandarin)",
    category: "drip-bags",
    price: "HK$100.00",
    originalPrice: "HK$130.00",
    image: "https://sofecoffee.com/cdn/shop/files/sofe_premium_drip_bag_colombia_VSCO.jpg",
    href: "/products/premium-drip-mandarin-single",
    shopifySlug: "Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-咖啡掛耳包-哥倫比亞-柑橘-1",
    badge: "Sale",
  },
  {
    id: "drip-premium-nicaragua-single",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Drip Bag - Nicaragua",
    category: "drip-bags",
    price: "HK$120.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_premium_drip_bag_nicatagua_VSCO.jpg",
    href: "/products/premium-drip-nicaragua-single",
    shopifySlug: "Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-咖啡掛耳包-尼加拉瓜-1",
    badge: null,
  },
  {
    id: "drip-premium-strawberry-single",
    name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 Drip Bag - Colombia (+ Strawberry)",
    category: "drip-bags",
    price: "HK$38.00",
    originalPrice: null,
    image: "https://sofecoffee.com/cdn/shop/files/sofe_premium_drip_bag_strawberry_VSCO.jpg",
    href: "/products/premium-drip-strawberry-single",
    shopifySlug: "Ⓟ-𝐏𝐫𝐞𝐦𝐢𝐮𝐦-咖啡掛耳包-哥倫比亞-士多啤梨-副本",
    badge: null,
  },

  // ===== Cascara Tea =====
  {
    id: "cascara",
    name: "Cascara - Coffee Cherry Fruit Tea",
    category: "cascara-tea",
    price: "HK$120.00",
    originalPrice: "HK$150.00",
    image: "https://sofecoffee.com/cdn/shop/files/sofe_cascura_can_50g_2025_pos_VSCO.jpg",
    href: "#",
    badge: "Sale",
  },

  // ===== Sofe Credits =====
  {
    id: "sofe-credits",
    name: "Sofe Credits - Stored Value Card",
    category: "sofe-credits",
    price: "HK$500.00",
    originalPrice: null,
    image: "https://placehold.co/400x400/1a1a2e/c8a45c?text=Sofe+Credits",
    href: "/collections/sofe-credits",
    badge: null,
  },
]

export const categories = [
  { id: "new-arrival", name: "New Arrival", slug: "/collections/new-arrival" },
  { id: "espresso-beans", name: "NEW - Espresso Beans", slug: "/collections/espresso-beans" },
  { id: "espresso-beans", name: "意式濃縮咖啡豆", slug: "/collections/%E6%84%8F%E5%BC%8F%E6%BF%83%E7%B8%AE%E5%92%96%E5%95%A1%E8%B1%86" },
  { id: "pour-over-beans", name: "Selected Coffee Beans", slug: "/collections/selected-beans" },
  { id: "drip-bags", name: "Coffee Drip Bag", slug: "/collections/coffee-drip-bag" },
  { id: "cold-brew-bags", name: "Cold Brew Bag", slug: "/collections/cold-brew-bag" },
  { id: "coffee-tools", name: "Coffee Tools", slug: "/collections/coffee-tools" },
  { id: "coffee-tools", name: "Coffee Tools", slug: "/collections/tools" },
  { id: "huskee", name: "Huskee", slug: "/collections/huskee" },
  { id: "special-offer", name: "Special Offer", slug: "/collections/%E7%89%B9%E5%83%B9%E7%94%A2%E5%93%81" },
  { id: "monthly-subscription", name: "Monthly Subscription", slug: "/collections/monthly-subscription" },
  { id: "monthly-subscription", name: "月訂優惠", slug: "/collections/%E6%9C%88%E8%A8%82%E5%84%AA%E6%83%A0" },
  { id: "monthly-subscription-beans", name: "月訂優惠 - 咖啡豆", slug: "/collections/%E6%9C%88%E8%A8%82%E5%84%AA%E6%83%A0-%E5%92%96%E5%95%A1%E8%B1%86" },
  { id: "cascara-tea", name: "Cascara Tea", slug: "/collections/cascara-tea" },
  { id: "sofe-credits", name: "Sofe Credits", slug: "/collections/sofe-credits" },
  { id: "premium-series", name: "Ⓟ 𝐏𝐫𝐞𝐦𝐢𝐮𝐦 特級咖啡豆系列", slug: "/collections/%E2%93%9F-%F0%9D%90%8F%F0%9D%90%AB%F0%9D%90%9E%F0%9D%90%A6%F0%9D%90%A2%F0%9D%90%AE%F0%9D%90%A6-%E7%89%B9%E7%B4%9A%E5%92%96%E5%95%A1%E8%B1%86%E7%B3%BB%E5%88%97" },
  { id: "airside", name: "Airside", slug: "/collections/airside" },
  { id: "xmas-2025", name: "Xmas 聖誕2025", slug: "/collections/xmas%E8%81%96%E8%AA%952025-%E9%99%90%E9%87%8F%E7%89%88%E5%92%96%E5%95%A1%E7%94%A2%E5%93%81" },
  { id: "shop-all", name: "Shop All", slug: "/collections/all" },
]

/**
 * Get products for a given category ID.
 * Handles special categories:
 *   - "shop-all" => all products
 *   - "new-arrival" => products with badge "NEW" or name starting with "NEW"
 *   - "premium-series" => products whose name contains "Ⓟ" or "Premium"
 *   - "airside", "xmas-2025" => empty (placeholder collections)
 */
export function getProductsByCategory(category) {
  if (category === "shop-all") return products
  if (category === "airside" || category === "xmas-2025") return []
  if (category === "new-arrival") {
    return products.filter(
      (p) => p.badge === "NEW" || p.name.startsWith("NEW")
    )
  }
  if (category === "premium-series") {
    return products.filter((p) => p.name.includes("Ⓟ") || p.name.includes("Premium"))
  }
  if (category === "special-offer") {
    return products.filter((p) => p.badge && p.badge.toLowerCase() === "sale")
  }
  if (category === "monthly-subscription") {
    return subscriptions.map((s) => ({
      id: s.id,
      name: `${s.name} - ${s.type}`,
      category: "monthly-subscription",
      price: s.price,
      originalPrice: s.originalPrice || null,
      image: s.image,
      href: s.href || "#",
      badge: s.save || null,
    }))
  }
  if (category === "monthly-subscription-beans") {
    return subscriptions
      .filter((s) => s.type && s.type.toLowerCase().includes("bean"))
      .map((s) => ({
        id: s.id,
        name: `${s.name} - ${s.type}`,
        category: "monthly-subscription",
        price: s.price,
        originalPrice: s.originalPrice || null,
        image: s.image,
        href: s.href || "#",
        badge: s.save || null,
      }))
  }
  return products.filter((p) => p.category === category)
}

/**
 * Map a collection slug (the last segment of /collections/:slug) to a category object.
 * Returns undefined if no match.
 */
export function getCategoryBySlug(slug) {
  return categories.find((c) => {
    const parts = c.slug.split("/")
    return parts[parts.length - 1] === slug
  })
}

export const subscriptions = [
  {
    id: "sub-db-3",
    name: "3 Months Subscription",
    type: "Coffee Drip Bag",
    price: "HK$1,450.00",
    originalPrice: "HK$1,800.00",
    image:
      "https://sofecoffee.com/cdn/shop/files/1779650387371-019e5b6d-7b0c-708c-8e31-5d26b1048609.png",
    href: "/products/3months_db_subscription",
    save: "Save 19%",
  },
  {
    id: "sub-db-6",
    name: "6 Months Subscription",
    type: "Coffee Drip Bag",
    price: "HK$2,580.00",
    originalPrice: "HK$3,600.00",
    image:
      "https://sofecoffee.com/cdn/shop/files/1779650466795-019e5b6d-b658-71a9-b773-d54705f0b075.png",
    href: "/products/6months_db_subscription",
    save: "Save 28%",
  },
  {
    id: "sub-db-12",
    name: "12 Months Subscription",
    type: "Coffee Drip Bag",
    price: "HK$4,500.00",
    originalPrice: "HK$7,200.00",
    image:
      "https://sofecoffee.com/cdn/shop/files/1779650854255-019e5b74-6bd0-7091-b0c9-cb6c36d7c79f.png",
    href: "/products/12months_db_subscription",
    save: "Save 37%",
  },
  {
    id: "sub-beans-3",
    name: "3 Months Subscription",
    type: "Pour Over Coffee Beans",
    price: "HK$780.00",
    originalPrice: "HK$870.00",
    image:
      "https://sofecoffee.com/cdn/shop/files/sofe_web_beans_3_months_2026.jpg",
    href: "/products/3months-bean-subscription",
    shopifySlug: "咖啡豆訂購3個月-副本",
    save: "Save 10%",
  },
  {
    id: "sub-beans-6",
    name: "6 Months Subscription",
    type: "Pour Over Coffee Beans",
    price: "HK$1,380.00",
    originalPrice: "HK$1,740.00",
    image:
      "https://sofecoffee.com/cdn/shop/files/sofe_web_beans_6_months_2026.jpg",
    href: "/products/6months-bean-subscription",
    shopifySlug: "6個月訂購-手沖咖啡豆",
    save: "Save 21%",
  },
  {
    id: "sub-beans-12",
    name: "12 Months Subscription",
    type: "Pour Over Coffee Beans",
    price: "HK$2,680.00",
    originalPrice: "HK$3,480.00",
    image:
      "https://sofecoffee.com/cdn/shop/files/sofe_web_beans_12_months_2026.jpg",
    href: "/products/12months-bean-subscription",
    shopifySlug: "12個月訂購-手沖咖啡豆",
    save: "Save 23%",
  },
]